# Generated by Django 5.1.7 on 2025-04-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_rename_description_reminder_body_reminder_recurring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='title',
        ),
        migrations.AddField(
            model_name='reminder',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='body',
            field=models.TextField(blank=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='recurring',
            field=models.BooleanField(default=False, verbose_name='recurring'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(verbose_name='time'),
        ),
    ]
