# Generated by Django 5.1.7 on 2025-04-17 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_remove_reminder_title_reminder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='body',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='recurring',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='time',
        ),
    ]
