# Generated by Django 5.1.7 on 2025-04-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_remove_reminder_body_remove_reminder_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='body',
            field=models.TextField(blank=True, verbose_name='body'),
        ),
    ]
