# Generated by Django 5.1.7 on 2025-04-24 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_reminder_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 18, 27, 46, 668555), verbose_name='datetime'),
        ),
    ]
