# Generated by Django 5.1.7 on 2025-04-24 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0009_alter_reminder_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='recurring',
            field=models.CharField(choices=[('no', 'No'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='no', max_length=255, verbose_name='recurring'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime'),
        ),
    ]
